// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripsLogUpdated.Models;

namespace TripsLogUpdated.Migrations
{
    [DbContext(typeof(TripsLogUpdatedContext))]
    [Migration("20211120220228_PopulateTripActivityTable")]
    partial class PopulateTripActivityTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TripsLogUpdated.Models.Accommodation", b =>
                {
                    b.Property<int>("AccommodationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccommodationEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccommodationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccommodationPhone")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.HasKey("AccommodationId");

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            AccommodationId = 1,
                            AccommodationName = "Camping"
                        },
                        new
                        {
                            AccommodationId = 2,
                            AccommodationEmail = "contact@staybridgesyutes.com",
                            AccommodationName = "Staybridge Suites",
                            AccommodationPhone = "(555)-123-9876"
                        },
                        new
                        {
                            AccommodationId = 3,
                            AccommodationEmail = "thelodge@whitefish.com",
                            AccommodationName = "The Lodge at Whitefish Lake"
                        });
                });

            modelBuilder.Entity("TripsLogUpdated.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            ActivityName = "Swimming"
                        },
                        new
                        {
                            ActivityId = 2,
                            ActivityName = "Hiking"
                        },
                        new
                        {
                            ActivityId = 3,
                            ActivityName = "Ride the subway"
                        },
                        new
                        {
                            ActivityId = 4,
                            ActivityName = "Go to Grand Central Station"
                        },
                        new
                        {
                            ActivityId = 5,
                            ActivityName = "Walk in the snow"
                        },
                        new
                        {
                            ActivityId = 6,
                            ActivityName = "Ice skate"
                        },
                        new
                        {
                            ActivityId = 7,
                            ActivityName = "Cross country skiing"
                        });
                });

            modelBuilder.Entity("TripsLogUpdated.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DestinationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            DestinationName = "Olympic Peninsula"
                        },
                        new
                        {
                            DestinationId = 2,
                            DestinationName = "New York"
                        },
                        new
                        {
                            DestinationId = 3,
                            DestinationName = "Whitefish, Montana"
                        });
                });

            modelBuilder.Entity("TripsLogUpdated.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("TripId");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            TripId = 1,
                            AccommodationId = 1,
                            DestinationId = 1,
                            EndDate = new DateTime(2020, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 2,
                            AccommodationId = 2,
                            DestinationId = 2,
                            EndDate = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 3,
                            AccommodationId = 3,
                            DestinationId = 3,
                            EndDate = new DateTime(2021, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TripsLogUpdated.Models.TripActivity", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.HasKey("TripId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("TripActivities");

                    b.HasData(
                        new
                        {
                            TripId = 1,
                            ActivityId = 1
                        },
                        new
                        {
                            TripId = 1,
                            ActivityId = 2
                        },
                        new
                        {
                            TripId = 2,
                            ActivityId = 3
                        },
                        new
                        {
                            TripId = 2,
                            ActivityId = 4
                        },
                        new
                        {
                            TripId = 3,
                            ActivityId = 5
                        },
                        new
                        {
                            TripId = 3,
                            ActivityId = 6
                        },
                        new
                        {
                            TripId = 3,
                            ActivityId = 7
                        });
                });

            modelBuilder.Entity("TripsLogUpdated.Models.Trip", b =>
                {
                    b.HasOne("TripsLogUpdated.Models.Accommodation", "Accommodation")
                        .WithMany("Trips")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripsLogUpdated.Models.Destination", "Destination")
                        .WithMany("Trips")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TripsLogUpdated.Models.TripActivity", b =>
                {
                    b.HasOne("TripsLogUpdated.Models.Activity", "Activity")
                        .WithMany("TripActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripsLogUpdated.Models.Trip", "Trip")
                        .WithMany("TripActivities")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
